[package]
authors = ["simdimdim <simdimdim@gmail.com>"]
default-run = "main"
edition = "2018"
name = "conrod-adhoc"
resolver = "2"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
conrod = "0.62.1"
conrod_core = {path = "../conrod/conrod_core"}
conrod_example_shared = {path = "../conrod/backends/conrod_example_shared"}
conrod_piston = {path = "../conrod/backends/conrod_piston"}

serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
serde_with = { version = "1.9.1", features = ["json", "macros"] }

# futures = "0.3.15"
# tokio = { version = "1.6.1", features = ["fs", "macros", "rt-multi-thread"] }
directories-next = "2.0.0"

[target.'cfg(linux)'.dependencies.sdl2]
features = []
version = "0.34.5"

[target.'cfg(not(linux))'.dependencies.sdl2]
features = ["bundled", "use-vcpkg"]
version = "0.34.5"

[dependencies.piston_window]
default-features = false
version = "0.120.0"

[dependencies.pistoncore-sdl2_window]
git = "https://github.com/PistonDevelopers/sdl2_window"
